module.exports = {
    UFN_FACEBOOKPOST_SEL: "select * from ufn_facebookpost_sel($take, $skip, $where, $order, $corporation);",
    UFN_FACEBOOKPOST_TOTALRECORDS: "select * from ufn_facebookpost_totalrecords($where, $corporation);",
    UFN_FACEBOOKPOST_EXPORT: "select * from ufn_facebookpost_export($where, $order, $corporation);",
    QUERY_AUTH: "select us.doctype, us.docnumber, ous.roleid, org.description orgdesc, corp.description corpdesc, ous.corpid, ous.orgid, us.userid, us.usr, us.pwd, us.firstname, us.lastname, us.email, us.status, ous.redirect, role.description roledesc from usr us inner join orguser ous on ous.userid = us.userid inner join org org on org.orgid = ous.orgid inner join corp corp on corp.corpid = ous.corpid inner join role role on role.roleid = ous.roleid where us.usr = $usr and ous.bydefault limit 1",
    USN_USER_INS: "SELECT * FROM ufn_user_ins($id, $usr, $doctype, $docnum, $pwd, $firstname, $lastname, $email, $pwdchangefirstlogin, $type, $status, $username, $operation, $redirect, $company)",
    UFN_USERS_SEL: "select * from ufn_users_sel($classification, $startdate, $enddate, $corporation);",
    UFN_USER_SEL: "select * from ufn_user_sel($facebookuserid);",
    UFN_FACEBOOKPOST_USERID_SEL: "select * from ufn_facebookpost_userid_sel($userid);",
    UFN_UPDATE_ANSWER_FBPOST: "update facebookpost set answered = $answered where facebookpostid = $facebookpostid",
    QUERY_AUTHENTICATED: "select us.userid, us.usr, us.doctype, us.docnum, us.pwd, us.firstname, us.lastname, us.email, us.status, ou.corpid, ou.orgid, org.description orgdesc, corp.description corpname from usr us left join orguser ou on ou.userid = us.userid left join org org on org.orgid = ou.orgid left join corp corp on corp.corpid = ou.corpid where us.usr = $usr and ou.bydefault = true",
    UFN_USERZYX_SEL: "select * from ufn_user_sel($corpid, $orgid, $id, $username, $applicationid, $all)",
    UFN_CORP_ORG_SEL: "SELECT * FROM ufn_corp_org_sel($corpid,$id,$username,$applicationid,$all)",
    UFN_ROLE_LST: "SELECT * FROM ufn_role_lst($corpid, $orgid)",
    UFN_COMMUNICATIONCHANNEL_LST: "SELECT * FROM ufn_communicationchannel_lst($corpid, $orgid)",
    UFN_USER_SUPERVISOR_LST: "SELECT * FROM ufn_user_supervisor_lst($corpid, $orgid, $userid)",
    UFN_APPS_DATA_SEL: "SELECT * FROM UFN_APPS_DATA_SEL($roleid)",
    UFN_ORGUSER_SEL: "SELECT * FROM ufn_orguser_sel($corpid, $orgid, $userid, $username, $applicationid, $all)",
    UFN_CONVERSATION_SEL_TICKETSBYUSER: "SELECT * FROM ufn_conversation_sel_ticketsbyuser_movil($corpid, $orgid, $userid, true, $origin, $status)",
    UFN_USERTOKEN_SEL: "SELECT * FROM ufn_usertoken_sel($corpid,$orgid,$userid, $token)",
    UFN_CONVERSATION_SEL_INTERACTION: "SELECT * FROM ufn_conversation_sel_interaction_movil($conversationid, $lock, $conversationold, true, $userid)",
    UFN_USERSTATUS_UPDATE: "SELECT * FROM ufn_userstatus_update($userid, $orgid, $type, $username, $status, $motive, $description)",
    UFN_CONVERSATION_INFORMATION_SEL: "SELECT * FROM ufn_conversation_information_sel_movil($conversationid)",
    UFN_CONVERSATION_PERSON_SEL: "SELECT * FROM ufn_conversation_person_sel_movil($personid)",
    UFN_PERSONADDINFO_SEL: "SELECT * FROM ufn_personaddinfo_sel($personid)",
    UFN_DOMAIN_LST_VALORES: "SELECT * FROM ufn_domain_lst_valores($corpid, $orgid, $domainname)",
    UFN_CONVERSATION_CHANGESTATUS: "SELECT * FROM ufn_conversation_changestatus($corpid, $orgid, $conversationid, $status, $obs, $motivo, $userid, $username)",
    UFN_CONVERSATION_LST_USRDELEGATE: "SELECT * FROM ufn_conversation_lst_usrdelegate2($corpid, $orgid, $userid)",
    UFN_CONVERSATION_REASSIGNTICKET: "SELECT * FROM ufn_conversation_reassignticket($conversationid, $newuserid, $userid, $username, $usergroup)",
    UFN_CONVERSATIONCLASSIFICATIONLIST_LEVEL1_SEL: "SELECT * FROM ufn_conversationclassificationlist_level1_sel($corpid, $orgid, $type)",
    UFN_CONVERSATIONCLASSIFICATIONLIST_LEVEL2_SEL: "SELECT * FROM ufn_conversationclassificationlist_level2_sel($corpid, $orgid, $type, $classificationid)",
    UFN_CONVERSATIONCLASSIFICATION_INS: "SELECT * FROM ufn_conversationclassification_ins($conversationid, $classificationid, $username, $operation)",
    UFN_CONVERSATIONID_SEL_TICKETSBYUSER: "SELECT * FROM ufn_conversationid_sel_ticketsbyuser_movil($conversationid, $corpid, $orgid)",
    UFN_USERSTATUS_UPDATE_ORG: "SELECT * FROM ufn_userstatus_update_org($userid, $orgidold, $orgidnew, $username)",
    UFN_ORGANIZATION_CHANGEORG_SEL: "SELECT * FROM ufn_organization_changeorg_sel($userid)",
    UFN_CONVERSATION_SEL_PREVIOUSTICKET: "SELECT * FROM ufn_conversation_sel_previousticket_movil($conversationid)",
    UFN_CONVERSATION_NOTES_INS: "SELECT * FROM ufn_conversation_notes_ins($id, $conversationid, $note, $status, $username, $operation)",
    UFN_CONVERSATION_NOTES_SEL: "SELECT * FROM ufn_conversation_notes_sel($conversationid)",
    UFN_PERSONADDINFO_SEL: "SELECT * FROM ufn_personaddinfo_sel($personid)",
    UFN_PROPERTY_SELBYNAME: "SELECT * FROM ufn_property_selbyname($corpid, $orgid, $propertyname)",
    UFN_CONVERSATION_CLASSIFICATION_SEL: "SELECT * FROM ufn_conversationclassification_sel($conversationid)",
    UFN_INAPPROPRIATE_WORDS_LST: "SELECT * FROM ufn_inappropriate_words_lst($corpid, $orgid)",
    UFN_QUICKREPLY_SEL: "SELECT * FROM ufn_quickreply_sel($corpid,$orgid,0,$username,$applicationid, true)",
    UFN_SECURITYRULES_ACTIVE: "SELECT * FROM ufn_securityrules_active($corpid)",
    UFN_USR_UPDATEPWD: "SELECT * FROM ufn_usr_updatepwd($userid ,$pwd,$username)",
    UFN_CHATFLOW_ISSELFBLOCK_SEL: "SELECT * FROM ufn_chatflow_isselfblock_sel($corpid, $orgid, $communicationchannelid)",
    UFN_QUICKREPLY_LIST_SEL: "SELECT * FROM ufn_quickreply_list_sel($corpid,$orgid,$classificationid,$all)",
    UFN_PERSONADDINFO_INS: "select * from ufn_personaddinfo_ins($corpid, $orgid, $personid, $id, $addinfo, $status, $type, $username, $operation)",
    UFN_PERSON_INS: "SELECT * from  ufn_person_ins($personid, $corpid, $orgid, $groups, $status, $type, $persontype, $personstatus, $phone, $email, $birthday, $alternativephone, $alternativeemail, $documenttype, $documentnumber, $firstname, $lastname, $sex, $gender, $civilstatus, $occupation, $educationlevel, $referringpersonid, null, $username, $operation)",
    UFN_PERSON_INS2: "SELECT * from  ufn_person_ins($personid, $corpid, $orgid, $groups, $status, $type, $persontype, $personstatus, $phone, $email, $birthday, $alternativephone, $alternativeemail, $documenttype, $documentnumber, $firstname, $lastname, $sex, $gender, $civilstatus, $occupation, $educationlevel, $referringpersonid, $observation, $username, $operation)",
    UFN_CONVERSATION_STRUCTUREDMESSAGE_SEL: "SELECT * FROM ufn_conversation_structuredmessage_sel($corpid, $orgid, $communicationchannelid, $type)",
    UFN_CONVERSATION_SEL_TICKETSBYPERSON: "SELECT * FROM ufn_conversation_sel_ticketsbyperson_movil($corpid, $orgid, $personid, $conversationid)",
    QUERY_EMOJICONVERSATION_SEL_NOT_CC: "select string_agg(emojichar, ',') from emoji where communicationchannel not like concat('%', $communicationchanneltype, '%')",
    UFN_USERHANDOFF_SEL: "SELECT * FROM ufn_userhandoff_sel($corpid, $orgid, $communicationchannelid, $usergroup)",
    UFN_CONVERSATION_SEL_INTERACTION_BYINTERACTIONID: "SELECT * FROM ufn_conversation_sel_interaction_byinteractionid_movil($conversationid, $interactionid, $order)",
    UFN_PERSONADDINFO_SEL: "SELECT * FROM ufn_personaddinfo_sel($personid)",
    UFN_TABLEVARIABLECONFIGURATIONBYCHANNEL_SEL: "select * from ufn_tablevariableconfigurationbychannel_sel($corpid, $orgid, $communicationchannelid, $userid)",
    QUERY_GET_CLIENT_BY_PHONE: "select * from clientetmp where telefono = $phone order by clientetmpid desc",
    QUERY_GET_CLIENT_BY_ADDRESS: "select * from clientetmp where direccion = $address order by clientetmpid desc",
    QUERY_GUARDAR_PEDIDO: "update clientetmp set detalleultimopedido = $detalleultimopedido where codigocliente = $codigocliente",
    UFN_DOMAIN_LST_VALORES: "SELECT * FROM ufn_domain_lst_valores($corpid, $orgid, $domainname)",
    UFN_CONVERSATION_SEL_TICKETSBYUSER_FILTER_MOVIL: "SELECT * FROM ufn_conversation_sel_ticketsbyuser_filter_movil($corpid, $orgid, $start_createticket, $end_createticket, $channels, $conversationstatus, $displayname, $phone, $offset)",
    UFN_COMMUNICATIONCHANNEL_LST: "SELECT * FROM ufn_communicationchannel_lst($corpid, $orgid)",
    UFN_MESSAGETEMPLATE_LST: "SELECT * FROM ufn_messagetemplate_lst($corpid, $orgid, $type, $username)",
    UFN_LEAD_PERSON_INS: "SELECT * FROM ufn_lead_person_ins($corpid, $orgid, $id, $description, $type, $status, $expected_revenue, $date_deadline, $tags, $personcommunicationchannel, $priority, $conversationid, $columnid, $username, $index, $firstname, $lastname, $email, $phone, $personid, $userid, $leadproduct)",
    UFN_USERTOKEN_INS: "select * from ufn_usertoken_ins($userid, $token, $origin)",
    UFN_USERSTATUS_UPDATE: "select * from ufn_userstatus_update($userid, $orgid, $type, $username, $status, $motive, $description)",
    UFN_GET_TOKEN_LOGGED_MOVIL: "select * from ufn_get_token_logged_movil($userid)",
    QUERY_UPDATE_PERSON_BY_HSM: "UPDATE person pe SET firstcontact = CASE WHEN pe.firstcontact IS NULL THEN NOW() else pe.firstcontact END, lastcontact = NOW() where pe.personid = $personid and pe.corpid = $corpid and pe.orgid = $orgid;",
    UFN_PRODUCTCATALOG_SEL: "select * from ufn_productcatalog_sel_normal($corpid,$orgid,$id,$category,$username,$all)"
    // ufn_conversation_fix: "SELECT * FROM ufn_conversation_fix($data::json)",
    // ufn_interaction_fix: "SELECT * FROM ufn_interactionrestore_fix($data::json)",
    // ufn_userstatus_update_fix: "SELECT * FROM ufn_userstatus_update_fix($data::json)",
    // test: "select datetimecreated, interactionrestoreid, personid, content, source, conversationid from interactionrestore order by personid, datetimecreated asc",
}