pipeline {
    agent any

    tools {
        nodejs '14.21.3'
    }

    stages {
        /*stage('Build') {
            steps {
                sh 'rsync -av --delete * /var/www/html/api-laraigo-dev'
            }
        }*/
        stage('Deploy') {
            steps {
                
                script {
                    withCredentials([sshUserPrivateKey(credentialsId: 'root-ssh-key', keyFileVariable: 'SSH_KEY')]) {
                        sh """
                            ssh -i \$SSH_KEY root@your-server-ip 'cd /var/www/html/api-laraigo-dev && ls && pm2 list'
                        """
                    }
                }
            }
        }
    }
}
