pipeline {
    agent any

    tools {
        nodejs '14.21.3'
    }

    stages {
        stage('Build') {
            steps {
                sh 'rsync -av --delete * /var/www/html/api-laraigo-dev'
            }
        }
        stage('Deploy') {
            steps {
                sh ' pm2 -v'
                //sh '/root/.nvm/versions/node/v14.21.3/bin/pm2 restart 0'
            }
        }
    }
}
