module.exports = {
    UFN_FACEBOOKPOST_SEL: "select * from ufn_facebookpost_sel($take, $skip, $where, $order, $corporation, $offset);",
    UFN_FACEBOOKPOST_TOTALRECORDS: "select * from ufn_facebookpost_totalrecords($where, $corporation);",
    UFN_FACEBOOKPOST_EXPORT: "select * from ufn_facebookpost_export($where, $order, $corporation, $offset);",
    USN_USER_INS:  "SELECT * FROM ufn_user_ins($id, $usr, $doctype, $docnum, $pwd, $firstname, $lastname, $email, $pwdchangefirstlogin, $type, $status, $username, $operation, $redirect, $company)",
    UFN_DOMAIN_LST_VALORES: "select * from ufn_domain_lst_valores(1, 1, $domainname);",
    UFN_USERS_SEL: "select * from ufn_users_sel($classification, $startdate, $enddate, $corporation);",
    UFN_USER_SEL: "select * from ufn_user_sel($facebookuserid, $offset);",
    UFN_FACEBOOKPOST_USERID_SEL: "select * from ufn_facebookpost_userid_sel($userid);",
    UFN_UPDATE_ANSWER_FBPOST: "update facebookpost set answered = $answered where facebookpostid = $facebookpostid",
    QUERY_AUTHENTICATED: "select us.userid, us.usr, us.doctype, us.docnum, us.pwd, us.firstname, us.lastname, us.email, us.status, us.company, ou.orgid, org.description orgname from usr us left join orguser ou on ou.userid = us.userid left join org org on org.orgid = ou.orgid where us.usr = $usr and (ou.bydefault = true or ou.bydefault is null)",
    UFN_USERZYX_SEL: "select * from ufn_analytics_user_sel($corpid, $orgid, $id, $username, $applicationid, $all, $corporation)",
    UFN_CORP_ORG_SEL: "SELECT * FROM ufn_corp_org_sel($corpid,$id,$username,$applicationid,$all)",
    UFN_ROLE_LST: "SELECT * FROM ufn_role_lst($corpid, $orgid)",
    UFN_COMMUNICATIONCHANNEL_LST: "SELECT * FROM ufn_communicationchannel_lst($corpid, $orgid)",
    UFN_USER_SUPERVISOR_LST: "SELECT * FROM ufn_user_supervisor_lst($corpid, $orgid, $userid)",
    UFN_APPS_DATA_SEL: "SELECT * FROM UFN_APPS_DATA_SEL($roleid)",
    UFN_ORGUSER_SEL: "SELECT * FROM ufn_orguser_sel($corpid, $orgid, $userid, $username, $applicationid, $all)",
    UFN_ANALYTICS_USER_INS: "select * from ufn_analytics_user_ins($id, $usr, $doctype, $docnum, $pwd, $firstname, $lastname, $email, $pwdchangefirstlogin, $type, $status, $username, $operation, $redirect, $company, $corporation, $role)",
    UFN_DASHBOARD_ANALYTICS_SUMMARY: "SELECT * FROM ufn_dashboard_analytics_summary($corporation, $postid, $startdate, $enddate)",
    UFN_DASHBOARD_ANALYTICS_NLCSUBCLASS: "SELECT * FROM ufn_dashboard_analytics_nlcsubclass($corporation, $postid, $startdate, $enddate)",
    UFN_DASHBOARD_ANALYTICS_NLUEMOTIONS: "SELECT * FROM ufn_dashboard_analytics_nluemotions($corporation, $postid, $startdate, $enddate)",
    UFN_FACEBOOKROOTPOST_SEL: "SELECT * FROM ufn_facebookrootpost_sel($corporation, $offset)",
    UFN_ENELRECLAMOS_INS: "SELECT * FROM ufn_enelreclamos_ins($processcontrolid, $tmpjson::json, $typedata)",
    UFN_PROCESSCONTROL_UPD: "SELECT * FROM ufn_processcontrol_upd($processcontrolid, $title)",
    UFN_PROCESSCONTROL_SEL: "SELECT * FROM ufn_processcontrol_sel($offset)",
    UFN_PROCESS_CLAIM: "SELECT * FROM ufn_process_claim($id, $typedata)",
    UFN_ENELRECLAMOS_SEL: "SELECT * FROM ufn_enelreclamos_sel($processcontrolid )",   
    UFN_ENELINGRESADOS_SEL: "SELECT * FROM ufn_enelingresados_sel($processcontrolid)",   
    UFN_ENELRESPONDIDOS_SEL: "SELECT * FROM ufn_enelrespondidos_sel($processcontrolid)", 
    UFN_GENERIC_TABLE_SEL: "select * from ufn_generic_table_sel()", 
    UFN_GENERIC_COLUMNS_SEL: "select * from ufn_generic_columns_sel($table)", 
    UFN_LOADTEMPLATE_INS: "SELECT * FROM ufn_loadtemplate_ins($corpid, $orgid, $loadtemplateid, $name, $description, $json_detail, $type, $status, $operation, $username, $tablename, $referencefilename, $json_export, $callbackfunction, $delimeter, $cleanbeforeload)",
    UFN_LOADTEMPLATE_SEL: "SELECT * FROM loadtemplate where status = 'ACTIVO'",
    QUERY_UPD_MAILATTACHMENT: "update mailattachment set successprocess = $successprocess, processingcomment = $processingcomment where mailattachmentid = $mailattachmentid",
    QUERY_SEL_MAILATTACHEMENT: "select mi.subject, mi.from, to_char(mi.datecreated - INTERVAL '5 hour', 'DD/MM/YYYY  HH24:MI:SS') maildate,ma.name, ma.storagepath, case when ma.successprocess is null then 'PENDIENTE' when ma.successprocess = true then 'SI' else 'NO' end processed, ma.processingcomment from mailattachment ma inner join mailinformation mi on mi.mailinformationid = ma.mailinformationid order by mi.datecreated desc;",
    QUERY_INS_PROCESS: "insert into processcontrol (title, uploaddate, status, createdate, createby, changedate, changeby, typedata) values ($title, NOW(), 'ACTIVO', NOW(), 'apidataloader', NOW(), 'apidataloader', $typedata) returning processcontrolid"
    // UFN_LOADTEMPLATE_SEL: "select * from ufn_loadtemplate_sel($corpid, $orgid, $username, $applicationid, $where, $order, $id, $take, $skip)",
}