pipeline {
    agent any

    tools {
        nodejs '14.21.3'
    }

    stages {
        stage('Build') {
            steps {
                sh 'sudo rsync -av --delete * /var/www/html/api-laraigo-test'
            }
        }
        stage('Deploy') {
            steps {
                sh 'cd /var/www/html/api-laraigo-test'
                sh 'npm install'
                sh 'sudo pm2 restart 1'
            }
        }
    }
}
